
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  host: localhost
  username: pguser
  password: pguser
  database: bridge

test:
  <<: *default
  database: bridge_test

production:
  <<: *default
  database: bridge_production
